[workspace]
channels = [ "https://prefix.dev/conda-forge", ]
name = "tracking-demo"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[dependencies] 
kalman = { path = "." }

[tasks] 
start = "tracking-main"

[package] 
name = "kalman"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-python"
version = "*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.host-dependencies] 
hatchling = "==1.26.3"

[package.run-dependencies] 
opencv = ">=4.13.0,<5"
numpy = ">=2.4.2,<3"
pandas = ">=3.0.1,<4"
pyyaml = ">=6.0.3,<7"
